version: '3'
services:
  web:
    build:
      context: .
    command: uvicorn api:app --host 0.0.0.0
    networks:
      - devnet
    volumes:
      - ./db:/src/db/
    labels:
      caddy: test.example.com
      caddy.reverse_proxy: "{{upstreams 8000}}"
    ports:
      - "8000:8000"

networks:
  devnet:
    external: true
