version: "3.3"

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
